{
  "hash": "164fe2ce9c6b25f1a902c3a2ca036c99",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Pengujian Intensitas Hue dengan Scoring Test'\nauthor: \"Tim Pengampu Praktikum Uji Sensoris\"\ndate: \"2026-09-14\"\noutput:\n  html_document: default\n  pdf_document: default\nsubtitle: One-Way ANOVA dan uji lanjut LSD beserta notasi huruf\neditor_options:\n  markdown:\n    wrap: 72\n---\n\n## Tujuan Pembelajaran\n\nSetelah sesi ini, mahasiswa akan mampu:\n\n| Mengetahui | Memahami | Melakukan |\n|------------------------|------------------------|------------------------|\n| Tiga unsur tristimuli warna: *hue*, *value*, dan *chroma* | Mengapa perubahan warna adalah milik sinar, bukan milik benda (metameri) | Menyusun tabulasi data beserta $T_a$, $T_b$, dan rata-rata |\n| Perbedaan *scoring difference test* dan *ranking test* | Arah skala kategori dan akibatnya pada penafsiran rata-rata | Menghitung FK, JKS, JKT, JKE, KTS, KTE, dan F-hitung |\n| Rumus derajat bebas DBS, DBT, dan DBE | Mengapa uji lanjut hanya dilakukan bila ANOVA signifikan | Membandingkan F-hitung dengan F-tabel dan menarik kesimpulan |\n| Prinsip uji lanjut LSD | Mengapa nilai $t$ untuk LSD diambil dua sisi | Menghitung LSD dan menyusun notasi huruf antar sampel |\n\n## Sekilas tentang Penilaian Warna\n\nWarna timbul dari tiga rangsangan yang bekerja serentak, disebut\n**tristimuli**:\n\n| Unsur | Definisi |\n|------------------------------------|------------------------------------|\n| *Hue* | Jenis warna, yaitu panjang gelombang yang paling banyak dipancarkan. Sinar tampak berkisar 380–770 m$\\mu$ |\n| *Value* (*lightness*) | Gelap terangnya warna, yaitu jumlah sinar yang dipancarkan |\n| *Chroma* | Intensitas warna, yaitu tingkat kemurnian *hue* |\n\nDua produk bisa memiliki *hue* yang sama, misalnya hijau, tetapi\n*value* atau *chroma* berbeda. Bila dua produk diberi pewarna dengan\nkonsentrasi berbeda, *hue* dan *chroma*-nya sama sedangkan *value*-nya\nberbeda.\n\nWarna yang tampak bergantung pada tiga hal di luar bendanya sendiri:\n\n| Unsur | Akibat pada penilaian |\n|------------------------------------|------------------------------------|\n| **Sumber sinar** | Benda yang dipindahkan ke jenis penyinaran lain akan tampak berubah warna. Peristiwa ini disebut **metameri**: perubahan warna adalah milik sinar, bukan milik bendanya |\n| **Obyek** | Permukaan halus dan kasar memantulkan cahaya berbeda. Pada benda tiga dimensi, tidak seluruh permukaan menerima penyinaran yang sama |\n| **Karakteristik visual panelis** | Tiga tipe sel *cone* sensitif pada panjang gelombang pendek, menengah, dan panjang. Kecepatan adaptasi terhadap perubahan penyinaran berbeda antar orang |\n\nKarena itu ukuran objek, wadah, sumber sinar, dan kesadaran panelis\nwajib dikendalikan. Kalau *booth* satu lebih terang daripada yang lain,\nyang terukur sebagian adalah pencahayaan, bukan sampelnya.\n\nMetode yang dipakai adalah **scoring test dengan skala kategori**.\nBedanya dengan *ranking test*: pada *scoring*, panelis boleh memberi\nnilai **sama** untuk sampel berbeda, sedangkan pada *ranking* tidak\nboleh ada peringkat kembar.\n\nSkala kategori yang digunakan mengikuti contoh pada modul, dengan tujuh\nkategori:\n\n| Nilai | Kategori |\n|:-----:|------------------------------------|\n| 1 | Amat sangat pekat |\n| 2 | Sangat pekat |\n| 3 | Pekat |\n| 4 | Sedikit pekat |\n| 5 | Agak pekat |\n| 6 | Agak tidak pekat |\n| 7 | Tidak pekat |\n\n> **Perhatikan arah skalanya!** Nilai **kecil** berarti intensitas\n> *hue* **tinggi**. Jadi sampel dengan rata-rata skor terendah adalah\n> sampel yang **paling pekat**, bukan yang paling pudar. Seluruh\n> perhitungan ANOVA dan LSD berjalan sama saja untuk arah skala mana\n> pun, tetapi **penafsiran** hasilnya terbalik. Inilah kesalahan yang\n> paling sering muncul pada pembahasan laporan.\n\nData yang akan kita gunakan berasal dari penilaian **20 panelis**\nterhadap **5 sampel** santan encer yang diberi pewarna dengan\nkonsentrasi berbeda, dengan kode tiga digit.\n\n| Kolom | Arti |\n|------------------------------------|------------------------------------|\n| `panelis` | Nama atau kode panelis |\n| `sampel` | Kode tiga digit sampel |\n| `skor` | Skor kategori intensitas *hue*, bilangan bulat 1 sampai 7 |\n\nData tersimpan pada file `acara6_hue.xlsx`, lembar **Data**. Untuk\nmenginput data kelompok Anda sendiri, gunakan\n`template_input_acara6.xlsx`.\n\n## Memuat Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(readxl)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhue <- as.data.frame(read_excel(\"assets/data/acara6_hue.xlsx\",\n                                sheet = \"Data\"))\n\nhue$panelis <- as.factor(hue$panelis)\nhue$sampel  <- as.factor(hue$sampel)\n\nstr(hue)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t100 obs. of  3 variables:\n $ panelis: Factor w/ 20 levels \"Panelis 01\",\"Panelis 02\",..: 1 1 1 1 1 2 2 2 2 2 ...\n $ sampel : Factor w/ 5 levels \"415\",\"537\",\"692\",..: 4 2 3 5 1 4 2 3 5 1 ...\n $ skor   : num  3 2 4 3 5 2 2 2 3 4 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(hue)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"panelis\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"sampel\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"skor\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Panelis 01\",\"2\":\"784\",\"3\":\"3\",\"_rn_\":\"1\"},{\"1\":\"Panelis 01\",\"2\":\"537\",\"3\":\"2\",\"_rn_\":\"2\"},{\"1\":\"Panelis 01\",\"2\":\"692\",\"3\":\"4\",\"_rn_\":\"3\"},{\"1\":\"Panelis 01\",\"2\":\"863\",\"3\":\"3\",\"_rn_\":\"4\"},{\"1\":\"Panelis 01\",\"2\":\"415\",\"3\":\"5\",\"_rn_\":\"5\"},{\"1\":\"Panelis 02\",\"2\":\"784\",\"3\":\"2\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n> **Think-aloud:** \"Saya periksa dua hal sebelum menghitung. Pertama\n> `table(hue$panelis, hue$sampel)` harus berisi 1 di setiap sel, karena\n> rumus derajat bebas pada modul mengandaikan setiap panelis menilai\n> setiap sampel tepat satu kali. Kedua `range(hue$skor)` harus di dalam\n> 1 sampai 7; skor 0 atau 8 biasanya berarti panelis mengisi borang\n> acara lain.\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(hue$panelis, hue$sampel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            \n             415 537 692 784 863\n  Panelis 01   1   1   1   1   1\n  Panelis 02   1   1   1   1   1\n  Panelis 03   1   1   1   1   1\n  Panelis 04   1   1   1   1   1\n  Panelis 05   1   1   1   1   1\n  Panelis 06   1   1   1   1   1\n  Panelis 07   1   1   1   1   1\n  Panelis 08   1   1   1   1   1\n  Panelis 09   1   1   1   1   1\n  Panelis 10   1   1   1   1   1\n  Panelis 11   1   1   1   1   1\n  Panelis 12   1   1   1   1   1\n  Panelis 13   1   1   1   1   1\n  Panelis 14   1   1   1   1   1\n  Panelis 15   1   1   1   1   1\n  Panelis 16   1   1   1   1   1\n  Panelis 17   1   1   1   1   1\n  Panelis 18   1   1   1   1   1\n  Panelis 19   1   1   1   1   1\n  Panelis 20   1   1   1   1   1\n```\n\n\n:::\n\n```{.r .cell-code}\nrange(hue$skor)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1 6\n```\n\n\n:::\n:::\n\n\n## Tabulasi Data\n\n$T_a$ adalah jumlah nilai per kolom (per sampel) dan $T_b$ adalah\njumlah nilai per baris (per panelis).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# tabel silang panelis x sampel, seperti Tabel 3.3 pada modul\ntabulasi <- hue %>%\n  pivot_wider(names_from = sampel, values_from = skor) %>%\n  as.data.frame()\n\ntabulasi$Tb <- rowSums(tabulasi[, -1])\ntabulasi\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"panelis\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"784\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"537\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"692\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"863\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"415\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Tb\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Panelis 01\",\"2\":\"3\",\"3\":\"2\",\"4\":\"4\",\"5\":\"3\",\"6\":\"5\",\"7\":\"17\"},{\"1\":\"Panelis 02\",\"2\":\"2\",\"3\":\"2\",\"4\":\"2\",\"5\":\"3\",\"6\":\"4\",\"7\":\"13\"},{\"1\":\"Panelis 03\",\"2\":\"2\",\"3\":\"2\",\"4\":\"1\",\"5\":\"3\",\"6\":\"4\",\"7\":\"12\"},{\"1\":\"Panelis 04\",\"2\":\"2\",\"3\":\"3\",\"4\":\"3\",\"5\":\"4\",\"6\":\"4\",\"7\":\"16\"},{\"1\":\"Panelis 05\",\"2\":\"2\",\"3\":\"2\",\"4\":\"3\",\"5\":\"3\",\"6\":\"3\",\"7\":\"13\"},{\"1\":\"Panelis 06\",\"2\":\"2\",\"3\":\"2\",\"4\":\"4\",\"5\":\"4\",\"6\":\"3\",\"7\":\"15\"},{\"1\":\"Panelis 07\",\"2\":\"1\",\"3\":\"3\",\"4\":\"2\",\"5\":\"3\",\"6\":\"4\",\"7\":\"13\"},{\"1\":\"Panelis 08\",\"2\":\"2\",\"3\":\"2\",\"4\":\"3\",\"5\":\"2\",\"6\":\"5\",\"7\":\"14\"},{\"1\":\"Panelis 09\",\"2\":\"2\",\"3\":\"2\",\"4\":\"3\",\"5\":\"4\",\"6\":\"4\",\"7\":\"15\"},{\"1\":\"Panelis 10\",\"2\":\"1\",\"3\":\"3\",\"4\":\"4\",\"5\":\"3\",\"6\":\"4\",\"7\":\"15\"},{\"1\":\"Panelis 11\",\"2\":\"3\",\"3\":\"2\",\"4\":\"2\",\"5\":\"4\",\"6\":\"5\",\"7\":\"16\"},{\"1\":\"Panelis 12\",\"2\":\"5\",\"3\":\"3\",\"4\":\"4\",\"5\":\"4\",\"6\":\"6\",\"7\":\"22\"},{\"1\":\"Panelis 13\",\"2\":\"1\",\"3\":\"2\",\"4\":\"3\",\"5\":\"4\",\"6\":\"5\",\"7\":\"15\"},{\"1\":\"Panelis 14\",\"2\":\"2\",\"3\":\"2\",\"4\":\"3\",\"5\":\"4\",\"6\":\"5\",\"7\":\"16\"},{\"1\":\"Panelis 15\",\"2\":\"3\",\"3\":\"2\",\"4\":\"4\",\"5\":\"4\",\"6\":\"6\",\"7\":\"19\"},{\"1\":\"Panelis 16\",\"2\":\"3\",\"3\":\"3\",\"4\":\"3\",\"5\":\"3\",\"6\":\"4\",\"7\":\"16\"},{\"1\":\"Panelis 17\",\"2\":\"4\",\"3\":\"3\",\"4\":\"3\",\"5\":\"5\",\"6\":\"6\",\"7\":\"21\"},{\"1\":\"Panelis 18\",\"2\":\"2\",\"3\":\"2\",\"4\":\"3\",\"5\":\"3\",\"6\":\"3\",\"7\":\"13\"},{\"1\":\"Panelis 19\",\"2\":\"3\",\"3\":\"3\",\"4\":\"3\",\"5\":\"3\",\"6\":\"3\",\"7\":\"15\"},{\"1\":\"Panelis 20\",\"2\":\"4\",\"3\":\"3\",\"4\":\"4\",\"5\":\"5\",\"6\":\"5\",\"7\":\"21\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTa <- hue %>%\n  group_by(sampel) %>%\n  summarise(Ta          = sum(skor),\n            Ta_kuadrat  = sum(skor)^2,\n            rata_rata   = mean(skor),\n            .groups     = \"drop\") %>%\n  as.data.frame()\n\nTa$rata_rata <- round(Ta$rata_rata, 2)\nTa\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"sampel\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"Ta\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"Ta_kuadrat\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"rata_rata\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"415\",\"2\":\"88\",\"3\":\"7744\",\"4\":\"4.40\"},{\"1\":\"537\",\"2\":\"48\",\"3\":\"2304\",\"4\":\"2.40\"},{\"1\":\"692\",\"2\":\"61\",\"3\":\"3721\",\"4\":\"3.05\"},{\"1\":\"784\",\"2\":\"49\",\"3\":\"2401\",\"4\":\"2.45\"},{\"1\":\"863\",\"2\":\"71\",\"3\":\"5041\",\"4\":\"3.55\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn <- length(unique(hue$sampel))    # jumlah sampel\np <- length(unique(hue$panelis))   # jumlah panelis\n\ntotal_skor         <- sum(hue$skor)\ntotal_skor_kuadrat <- sum(hue$skor^2)\n\nc(n = n, p = p, total = total_skor, total_kuadrat = total_skor_kuadrat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            n             p         total total_kuadrat \n            5            20           317          1129 \n```\n\n\n:::\n:::\n\n\n## Perhitungan ANOVA\n\nDerajat bebas mengikuti rumus pada modul:\n\n$$\nDBS = n - 1, \\qquad DBT = (n \\cdot p) - 1, \\qquad DBE = n(p - 1)\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndbs <- n - 1\ndbt <- (n * p) - 1\ndbe <- n * (p - 1)\n\nc(DBS = dbs, DBT = dbt, DBE = dbe)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDBS DBT DBE \n  4  99  95 \n```\n\n\n:::\n:::\n\n\nFaktor koreksi dan jumlah kuadrat:\n\n$$\nFK = \\frac{(\\sum X)^2}{n \\cdot p}, \\qquad\nJKS = \\frac{\\sum T_a^2}{p} - FK, \\qquad\nJKT = \\sum X^2 - FK, \\qquad\nJKE = JKT - JKS\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nFK  <- total_skor^2 / (n * p)\nJKS <- sum(Ta$Ta^2) / p - FK\nJKT <- total_skor_kuadrat - FK\nJKE <- JKT - JKS\n\nround(c(FK = FK, JKS = JKS, JKT = JKT, JKE = JKE), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     FK     JKS     JKT     JKE \n1004.89   55.66  124.11   68.45 \n```\n\n\n:::\n:::\n\n\nRata-rata kuadrat dan F-hitung:\n\n$$\nKTS = \\frac{JKS}{DBS}, \\qquad KTE = \\frac{JKE}{DBE}, \\qquad\nF_{hitung} = \\frac{KTS}{KTE}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nKTS <- JKS / dbs\nKTE <- JKE / dbe\nF_hitung <- KTS / KTE\n\nalpha   <- 0.05\nF_tabel <- qf(1 - alpha, dbs, dbe)   # setara =F.INV.RT(alpha; dbs; dbe)\n\nround(c(KTS = KTS, KTE = KTE, F_hitung = F_hitung,\n        F_tabel = F_tabel), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     KTS      KTE F_hitung  F_tabel \n  13.915    0.721   19.312    2.467 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_tabel <- data.frame(\n  sumber = c(\"Sampel\", \"Error\", \"Total\"),\n  db     = c(dbs, dbe, dbt),\n  JK     = round(c(JKS, JKE, JKT), 3),\n  KT     = c(round(KTS, 3), round(KTE, 3), NA),\n  F_hitung = c(round(F_hitung, 3), NA, NA),\n  F_tabel  = c(round(F_tabel, 3), NA, NA)\n)\nanova_tabel\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"sumber\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"db\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"JK\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"KT\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F_hitung\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"F_tabel\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Sampel\",\"2\":\"4\",\"3\":\"55.66\",\"4\":\"13.915\",\"5\":\"19.312\",\"6\":\"2.467\"},{\"1\":\"Error\",\"2\":\"95\",\"3\":\"68.45\",\"4\":\"0.721\",\"5\":\"NA\",\"6\":\"NA\"},{\"1\":\"Total\",\"2\":\"99\",\"3\":\"124.11\",\"4\":\"NA\",\"5\":\"NA\",\"6\":\"NA\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nSebagai pemeriksaan, hasil yang sama dapat diperoleh dengan `aov()`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel <- aov(skor ~ sampel, data = hue)\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            Df Sum Sq Mean Sq F value   Pr(>F)    \nsampel       4  55.66  13.915   19.31 1.18e-11 ***\nResiduals   95  68.45   0.721                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n> **Think-aloud:** \"Saya selalu menghitung manual dulu lalu\n> membandingkan dengan `aov()`. Kalau JKS dan JKE-nya tidak sama, yang\n> salah hampir selalu penyebut pada JKS: yang membagi $\\sum T_a^2$\n> adalah **jumlah panelis** $p$, bukan jumlah sampel $n$. Kesalahan ini\n> tidak akan terdeteksi dari besarnya angka, karena hasilnya tetap\n> masuk akal.\"\n\nHipotesis dan kesimpulannya:\n\n-   $H_0$ = tidak ada perbedaan signifikan di antara sampel\n-   $H_1$ = terdapat perbedaan signifikan di antara sampel\n-   $F_{hitung} > F_{tabel}$ $\\rightarrow$ $H_0$ ditolak, $H_1$\n    diterima\n\n\n::: {.cell}\n\n```{.r .cell-code}\nifelse(F_hitung > F_tabel,\n       \"F-hitung > F-tabel: H0 ditolak, ada perbedaan antar sampel\",\n       \"F-hitung < F-tabel: H0 diterima, tidak ada perbedaan antar sampel\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"F-hitung > F-tabel: H0 ditolak, ada perbedaan antar sampel\"\n```\n\n\n:::\n:::\n\n\n### *Hinge Question*\n\n> **Sebelum melanjutkan, jawablah:** Pada data ini sampel 537\n> memperoleh rata-rata skor 2,40 sedangkan sampel 415 memperoleh 4,40.\n> Manakah pernyataan yang benar?\n>\n> A)  Sampel 415 intensitas *hue*-nya paling tinggi karena skornya\n>     paling besar\\\n> B)  Sampel 537 intensitas *hue*-nya paling tinggi karena skor kecil\n>     berarti amat sangat pekat\\\n> C)  Keduanya tidak dapat dibandingkan karena kodenya berbeda\\\n> D)  Sampel 415 diberi pewarna paling banyak\n>\n> **Jawaban: B.** Skala kategorinya menurun: 1 = amat sangat pekat dan\n> 7 = tidak pekat. Jadi rata-rata **terkecil** menandakan intensitas\n> *hue* **tertinggi**. Perhitungan ANOVA sama sekali tidak terpengaruh\n> arah skala, tetapi kalimat pembahasan akan terbalik seluruhnya kalau\n> arah ini terlewat. Pilihan D juga salah karena panelis dinilai secara\n> buta terhadap perlakuan; kaitan dengan konsentrasi pewarna baru bisa\n> ditarik setelah kode dibuka lewat *cheat sheet*.\n\n## Uji Lanjut LSD\n\nUji lanjut hanya dilakukan **bila ANOVA signifikan**. Kalau $H_0$\nditerima, perhitungan dicukupkan sampai di sini.\n\n$$\nLSD = t_{(\\alpha/2,\\; DBE)} \\times \\sqrt{\\frac{2 \\cdot KTE}{p}}\n$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt_tabel <- qt(1 - alpha / 2, dbe)     # nilai t dua sisi\nLSD     <- t_tabel * sqrt(2 * KTE / p)\n\nround(c(t_tabel = t_tabel, LSD = LSD), 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nt_tabel     LSD \n  1.985   0.533 \n```\n\n\n:::\n:::\n\n\n> **Perhatikan nilai** $t$ **yang dipakai.** Modul menuliskan rumus\n> Excel `=T.INV(alpha; dbe)`. Fungsi `T.INV` mengembalikan nilai $t$\n> **satu sisi bagian kiri**, sehingga untuk $\\alpha = 0{,}05$ hasilnya\n> negatif, yaitu sekitar $-1{,}66$. Nilai yang dimaksud hampir pasti\n> nilai $t$ **dua sisi**, yang di Excel ditulis `=T.INV.2T(alpha; dbe)`\n> atau `=T.INV(1-alpha/2; dbe)`, dan di R adalah\n> `qt(1 - alpha/2, dbe)`. Pada data ini perbedaannya bukan sekadar soal\n> ketelitian: $t$ satu sisi menghasilkan LSD sekitar 0,45 sedangkan $t$\n> dua sisi menghasilkan sekitar 0,53, dan ada satu pasangan sampel yang\n> kesimpulannya berubah karenanya. Konfirmasikan hal ini kepada dosen\n> pengampu sebelum menghitung.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# selisih rata-rata antar seluruh pasangan sampel\nrata <- Ta$rata_rata\nnames(rata) <- as.character(Ta$sampel)\n\npasangan <- t(combn(names(rata), 2))\nbanding <- data.frame(\n  sampel_1 = pasangan[, 1],\n  sampel_2 = pasangan[, 2],\n  selisih  = round(abs(rata[pasangan[, 1]] - rata[pasangan[, 2]]), 2)\n)\nbanding$LSD       <- round(LSD, 2)\nbanding$kode      <- ifelse(banding$selisih > LSD, 1, 0)\nbanding$kesimpulan <- ifelse(banding$kode == 1,\n                             \"Berbeda signifikan\",\n                             \"Tidak berbeda signifikan\")\nbanding\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"sampel_1\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"sampel_2\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"selisih\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LSD\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"kode\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"kesimpulan\"],\"name\":[6],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"415\",\"2\":\"537\",\"3\":\"2.00\",\"4\":\"0.53\",\"5\":\"1\",\"6\":\"Berbeda signifikan\"},{\"1\":\"415\",\"2\":\"692\",\"3\":\"1.35\",\"4\":\"0.53\",\"5\":\"1\",\"6\":\"Berbeda signifikan\"},{\"1\":\"415\",\"2\":\"784\",\"3\":\"1.95\",\"4\":\"0.53\",\"5\":\"1\",\"6\":\"Berbeda signifikan\"},{\"1\":\"415\",\"2\":\"863\",\"3\":\"0.85\",\"4\":\"0.53\",\"5\":\"1\",\"6\":\"Berbeda signifikan\"},{\"1\":\"537\",\"2\":\"692\",\"3\":\"0.65\",\"4\":\"0.53\",\"5\":\"1\",\"6\":\"Berbeda signifikan\"},{\"1\":\"537\",\"2\":\"784\",\"3\":\"0.05\",\"4\":\"0.53\",\"5\":\"0\",\"6\":\"Tidak berbeda signifikan\"},{\"1\":\"537\",\"2\":\"863\",\"3\":\"1.15\",\"4\":\"0.53\",\"5\":\"1\",\"6\":\"Berbeda signifikan\"},{\"1\":\"692\",\"2\":\"784\",\"3\":\"0.60\",\"4\":\"0.53\",\"5\":\"1\",\"6\":\"Berbeda signifikan\"},{\"1\":\"692\",\"2\":\"863\",\"3\":\"0.50\",\"4\":\"0.53\",\"5\":\"0\",\"6\":\"Tidak berbeda signifikan\"},{\"1\":\"784\",\"2\":\"863\",\"3\":\"1.10\",\"4\":\"0.53\",\"5\":\"1\",\"6\":\"Berbeda signifikan\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nKolom `kode` mengikuti aturan notasi pada modul: selisih $<$ LSD diberi\nangka 0, selisih $>$ LSD diberi angka 1.\n\n## Notasi Huruf\n\nSampel dengan notasi huruf yang **sama** berarti tidak berbeda\nsignifikan; huruf yang **berbeda** berarti berbeda signifikan.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(\"agricolae\")\nlibrary(agricolae)\n\nlsd_hasil <- LSD.test(model, \"sampel\", alpha = alpha,\n                      console = FALSE, group = TRUE)\n\nnotasi <- lsd_hasil$groups\nnotasi$sampel <- rownames(notasi)\nnotasi <- notasi[, c(\"sampel\", \"skor\", \"groups\")]\nnames(notasi) <- c(\"sampel\", \"rata_rata\", \"notasi\")\nnotasi$rata_rata <- round(notasi$rata_rata, 2)\nnotasi\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"sampel\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"rata_rata\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"notasi\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"415\",\"2\":\"4.40\",\"3\":\"a\",\"_rn_\":\"415\"},{\"1\":\"863\",\"2\":\"3.55\",\"3\":\"b\",\"_rn_\":\"863\"},{\"1\":\"692\",\"2\":\"3.05\",\"3\":\"b\",\"_rn_\":\"692\"},{\"1\":\"784\",\"2\":\"2.45\",\"3\":\"c\",\"_rn_\":\"784\"},{\"1\":\"537\",\"2\":\"2.40\",\"3\":\"c\",\"_rn_\":\"537\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# urutkan dari rata-rata terkecil, yaitu intensitas hue tertinggi\nnotasi[order(notasi$rata_rata), ]\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"sampel\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"rata_rata\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"notasi\"],\"name\":[3],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"537\",\"2\":\"2.40\",\"3\":\"c\",\"_rn_\":\"537\"},{\"1\":\"784\",\"2\":\"2.45\",\"3\":\"c\",\"_rn_\":\"784\"},{\"1\":\"692\",\"2\":\"3.05\",\"3\":\"b\",\"_rn_\":\"692\"},{\"1\":\"863\",\"2\":\"3.55\",\"3\":\"b\",\"_rn_\":\"863\"},{\"1\":\"415\",\"2\":\"4.40\",\"3\":\"a\",\"_rn_\":\"415\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nCara membaca tabel ini:\n\n| Yang Anda lihat | Artinya |\n|------------------------------------|------------------------------------|\n| **Dua sampel bernotasi sama** | Selisih rata-ratanya lebih kecil daripada LSD; belum ada bukti keduanya berbeda |\n| **Dua sampel bernotasi berbeda** | Selisih rata-ratanya melebihi LSD; keduanya berbeda signifikan |\n| **Satu sampel bernotasi ganda**, misalnya `ab` | Sampel itu tidak berbeda dari kelompok `a` maupun kelompok `b`; posisinya di antara keduanya |\n| **Rata-rata paling kecil** | Intensitas *hue* paling tinggi, mengingat arah skalanya |\n\n## Grafik\n\n\n::: {.cell}\n\n```{.r .cell-code}\nringkas <- hue %>%\n  group_by(sampel) %>%\n  summarise(rata_rata = mean(skor),\n            se        = sd(skor) / sqrt(n()),\n            .groups   = \"drop\") %>%\n  left_join(notasi[, c(\"sampel\", \"notasi\")], by = \"sampel\") %>%\n  as.data.frame()\n\nggplot(ringkas, aes(x = reorder(sampel, rata_rata), y = rata_rata)) +\n  geom_col(fill = \"#2C7FB8\", width = 0.6) +\n  geom_errorbar(aes(ymin = rata_rata - se, ymax = rata_rata + se),\n                width = 0.15, colour = \"grey30\") +\n  geom_text(aes(label = notasi, y = rata_rata + se + 0.25),\n            size = 4.2) +\n  scale_y_continuous(limits = c(0, 7), breaks = 1:7) +\n  labs(title = \"Rata-Rata Skor Intensitas Hue Tiap Sampel\",\n       subtitle = paste0(\"Huruf berbeda = berbeda signifikan (LSD = \",\n                         round(LSD, 2),\n                         \"). Skor kecil = hue lebih pekat\"),\n       x = \"Kode sampel\", y = \"Rata-rata skor kategori\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](05_intensitas-hue_id_files/figure-html/unnamed-chunk-17-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(hue, aes(x = reorder(sampel, skor, FUN = mean), y = skor)) +\n  geom_boxplot(fill = \"grey90\", outlier.shape = NA) +\n  geom_jitter(width = 0.15, height = 0.12, alpha = 0.5,\n              colour = \"#2C7FB8\") +\n  scale_y_continuous(limits = c(1, 7), breaks = 1:7) +\n  labs(title = \"Sebaran Skor Tiap Sampel\",\n       subtitle = \"Titik digeser sedikit agar skor kembar tetap terlihat\",\n       x = \"Kode sampel\", y = \"Skor kategori\") +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](05_intensitas-hue_id_files/figure-html/unnamed-chunk-18-1.png){width=768}\n:::\n:::\n\n\n> **Mengapa titik-titiknya digeser (*jitter*)?** Karena skala kategori\n> hanya menghasilkan bilangan bulat, banyak panelis memberi skor yang\n> persis sama dan titiknya akan bertumpuk menjadi satu. Tanpa\n> penggeseran, grafik menyembunyikan berapa banyak panelis yang\n> sebenarnya ada di setiap nilai.\n\n## Menyusun Kesimpulan\n\nModul menyediakan dua kerangka kesimpulan yang harus keduanya ditulis.\n\n**Kesimpulan #1 (ANOVA).** Berdasarkan hasil analisis One-Way ANOVA\ndengan tingkat konfidensi 95%, F-hitung sampel (...) $>$ atau $<$\nF-tabel (...); $H_0$ ditolak atau diterima, maka $H_1$ diterima atau\nditolak, sehingga ada atau tidak ada perbedaan di antara sampel.\n\n**Kesimpulan #2 (LSD).** Untuk **setiap pasangan** sampel: berdasarkan\nanalisis Post-Hoc LSD, sampel (kode)-(kode), selisih rata-rata (...)\n$>$ atau $<$ LSD (...), dengan tingkat konfidensi 95%, maka $H_0$\nditolak atau diterima, sehingga ada atau tidak ada perbedaan signifikan\nantara sampel.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# bahan kalimat Kesimpulan #2, satu baris per pasangan\nbanding[, c(\"sampel_1\", \"sampel_2\", \"selisih\", \"LSD\", \"kesimpulan\")]\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"sampel_1\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"sampel_2\"],\"name\":[2],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"selisih\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"LSD\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"kesimpulan\"],\"name\":[5],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"415\",\"2\":\"537\",\"3\":\"2.00\",\"4\":\"0.53\",\"5\":\"Berbeda signifikan\"},{\"1\":\"415\",\"2\":\"692\",\"3\":\"1.35\",\"4\":\"0.53\",\"5\":\"Berbeda signifikan\"},{\"1\":\"415\",\"2\":\"784\",\"3\":\"1.95\",\"4\":\"0.53\",\"5\":\"Berbeda signifikan\"},{\"1\":\"415\",\"2\":\"863\",\"3\":\"0.85\",\"4\":\"0.53\",\"5\":\"Berbeda signifikan\"},{\"1\":\"537\",\"2\":\"692\",\"3\":\"0.65\",\"4\":\"0.53\",\"5\":\"Berbeda signifikan\"},{\"1\":\"537\",\"2\":\"784\",\"3\":\"0.05\",\"4\":\"0.53\",\"5\":\"Tidak berbeda signifikan\"},{\"1\":\"537\",\"2\":\"863\",\"3\":\"1.15\",\"4\":\"0.53\",\"5\":\"Berbeda signifikan\"},{\"1\":\"692\",\"2\":\"784\",\"3\":\"0.60\",\"4\":\"0.53\",\"5\":\"Berbeda signifikan\"},{\"1\":\"692\",\"2\":\"863\",\"3\":\"0.50\",\"4\":\"0.53\",\"5\":\"Tidak berbeda signifikan\"},{\"1\":\"784\",\"2\":\"863\",\"3\":\"1.10\",\"4\":\"0.53\",\"5\":\"Berbeda signifikan\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n> **Latihan menulis:** Selain kedua kesimpulan di atas, tambahkan satu\n> paragraf yang mengaitkan hasil dengan konsentrasi pewarna pada\n> *cheat sheet*. Apakah urutan intensitas *hue* menurut panelis sesuai\n> dengan urutan konsentrasi pewarna yang sebenarnya? Bila ada sampel\n> yang menyimpang, sebutkan kemungkinan penyebabnya dari tiga unsur\n> penentu warna yang dibahas di awal.\n\n## Latihan (You Do)\n\n### Latihan 1: Membaca Tabel ANOVA\n\n1.  Tampilkan ulang tabel ANOVA dan tunjukkan bahwa\n    $JKS + JKE = JKT$:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nc(JKS + JKE, JKT)\n```\n:::\n\n\n2.  Berapa persen keragaman total yang dijelaskan oleh perbedaan antar\n    sampel?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nround(100 * JKS / JKT, 1)\n```\n:::\n\n\nApa arti sisanya, dan dari mana keragaman itu berasal?\n\n### Latihan 2: Pasangan yang Tidak Berbeda\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsubset(banding, kode == 0)\n```\n:::\n\n\nUntuk pasangan yang tidak berbeda signifikan, berapa selisih\nkonsentrasi pewarna keduanya menurut *cheat sheet*? Apakah selisih itu\nmemang terlalu kecil untuk dibedakan mata?\n\n### Latihan 3: *Challenges*\n\n1.  Modul menggunakan One-Way ANOVA, sehingga perbedaan kebiasaan\n    menilai antar panelis masuk ke dalam error. Coba masukkan panelis\n    sebagai **blok**, lalu bandingkan KTE-nya:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- aov(skor ~ sampel + panelis, data = hue)\nsummary(model2)\n```\n:::\n\n\nKTE mana yang lebih kecil? Apa akibatnya pada nilai LSD dan pada\njumlah pasangan yang dinyatakan berbeda? Mengapa hasil ini masuk akal\nbila dikaitkan dengan materi baseline pada Acara 3?\n\n2.  Bandingkan LSD dengan uji Tukey, yang mengendalikan peluang salah\n    pada seluruh himpunan pasangan sekaligus:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTukeyHSD(model, \"sampel\")\n```\n:::\n\n\nManakah yang lebih longgar menyatakan perbedaan? Dengan 10 pasangan\nyang diuji sekaligus, mana yang lebih pantas dilaporkan?\n\n3.  Karena skor kategori bersifat ordinal, ulangi pengujian dengan uji\n    nonparametrik dan bandingkan kesimpulannya:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkruskal.test(skor ~ sampel, data = hue)\n```\n:::\n\n\nApakah kesimpulannya berubah? Kalau tidak, apa artinya bagi keputusan\nmemakai ANOVA pada data skala kategori?\n\n## Ringkasan\n\nDalam sesi ini kita telah mempelajari:\\\n- Tristimuli warna *hue*, *value*, dan *chroma*, serta perbedaan\nketiganya\\\n- Tiga unsur penentu warna yang tampak: sumber sinar, obyek, dan\nkarakteristik visual panelis, termasuk gejala metameri\\\n- Perbedaan *scoring difference test* dan *ranking test*, dan mengapa\nskor kembar diperbolehkan pada *scoring*\\\n- Arah skala kategori, di mana skor kecil berarti intensitas *hue*\ntinggi, serta akibatnya pada penafsiran\\\n- Perhitungan One-Way ANOVA secara manual: derajat bebas, FK, JKS, JKT,\nJKE, KTS, KTE, dan F-hitung, beserta pemeriksaannya dengan `aov()`\\\n- Uji lanjut LSD, termasuk penggunaan nilai $t$ dua sisi\\\n- Penyusunan notasi huruf dan cara membacanya, termasuk arti notasi\nganda seperti `ab`\n",
    "supporting": [
      "05_intensitas-hue_id_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}